#!/bin/bash

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"

source "$CONFIG_DIR/colors.sh" # Loads all defined colors
source $ITEM_DIR/icons.sh
# This is a demo config to show some of the most important commands more easily.
# This is meant to be changed and configured, as it is intentionally kept sparse.
# For a more advanced configuration example see my dotfiles:
# https://github.com/FelixKratz/dotfiles

##### Bar Appearance #####
# Configuring the general appearance of the bar, these are only some of the
# options available. For all options see:
# https://felixkratz.github.io/SketchyBar/config/bar
# If you are looking for other colors, see the color picker:
# https://felixkratz.github.io/SketchyBar/config/tricks#color-picker

sketchybar --add event window_change

sketchybar --bar height=34        \
                 blur_radius=30   \
                 position=top     \
                 sticky=off       \
                 padding_left=10  \
                 padding_right=10 \
                 color=$BAR_COLOR

##### Changing Defaults #####
# We now change some default values that are applied to all further items
# For a full list of all available item properties see:
# https://felixkratz.github.io/SketchyBar/config/items

# sketchybar --default icon.font="Hack Nerd Font:Bold:17.0"  \
sketchybar --default icon.font="Hack Nerd Font:Bold:17.0"  \
                     icon.color=$WHITE                     \
                     label.font="Hack Nerd Font:Bold:14.0" \
                     label.color=$WHITE                \
                     background.color=$ITEM_BG_COLOR       \
                     background.corner_radius=5            \
                     background.height=24                  \
                     padding_left=5                        \
                     padding_right=5                       \
                     label.padding_left=4                  \
                     label.padding_right=4                 \
                     icon.padding_left=4                   \
                     icon.padding_right=4

##### Adding Mission Control Space Indicators #####
# Now we add some mission control spaces:
# https://felixkratz.github.io/SketchyBar/config/components#space----associate-mission-control-spaces-with-an-item
# to indicate active and available mission control spaces

# SPACE_ICONS=("1" "2" "3" "4" "5" "6" "7" "8" "9" "10")
#
# for i in "${!SPACE_ICONS[@]}"
# do
#   sid=$(($i+1))
#   sketchybar --add space space.$sid left                                 \
#              --set space.$sid space=$sid                                 \
#                               icon=${SPACE_ICONS[i]}                     \
#                               background.color=0x44ffffff                \
#                               background.corner_radius=5                 \
#                               background.height=20                       \
#                               background.drawing=off                     \
#                               label.drawing=off                          \
#                               script="$PLUGIN_DIR/space.sh"              \
#                               click_script="yabai -m space --focus $sid"
# done
#
# ##### Adding Left Items #####
# # We add some regular items to the left side of the bar
# # only the properties deviating from the current defaults need to be set
#
# sketchybar --add item space_separator left                         \
#            --set space_separator icon=                            \
#                                  padding_left=10                   \
#                                  padding_right=10                  \
#                                  label.drawing=off                 \
#                                                                    \
#            --add item front_app left                               \
#            --set front_app       script="$PLUGIN_DIR/front_app.sh" \
#                                  icon.drawing=off                  \
#            --subscribe front_app front_app_switched
#
# ##### Adding Right Items #####
# # In the same way as the left items we can add items to the right side.
# # Additional position (e.g. center) are available, see:
# # https://felixkratz.github.io/SketchyBar/config/items#adding-items-to-sketchybar
#
# # Some items refresh on a fixed cycle, e.g. the clock runs its script once
# # every 10s. Other items respond to events they subscribe to, e.g. the
# # volume.sh script is only executed once an actual change in system audio
# # volume is registered. More info about the event system can be found here:
# # https://felixkratz.github.io/SketchyBar/config/events
#
# sketchybar --add item clock right                              \
#            --set clock   update_freq=10                        \
#                          icon=                                \
#                          script="$PLUGIN_DIR/clock.sh"         \
#                                                                \
#            --add item volume right                             \
#            --set volume  script="$PLUGIN_DIR/volume.sh"        \
#            --subscribe volume volume_change                    \
#                                                                \
#            --add item battery right                            \
#            --set battery script="$PLUGIN_DIR/battery.sh"       \
#                          update_freq=120                       \
#            --subscribe battery system_woke power_source_change

##### Finalizing Setup #####
# The below command is only needed at the end of the initial configuration to
# force all scripts to run the first time, it should never be run in an item script.

# _____________________________ NY CUSTOMIZATIONS _____________________________

# Register custom event - this will be use by sketchybar's space items as well as app_space.sh
sketchybar --add event window_change

# Space items
COLORS_SPACE=($COLOR_YELLOW $COLOR_CYAN $COLOR_MAGENTA $COLOR_WHITE $COLOR_BLUE $COLOR_RED $COLOR_GREEN)
LENGTH=${#ICONS_SPACE[@]}

for i in "${!ICONS_SPACE[@]}"
do
  sid=$(($i+1))
  PAD_LEFT=2
  PAD_RIGHT=2
  if [[ $i == 0 ]]; then
    PAD_LEFT=8
  elif [[ $i == $(($LENGTH-1)) ]]; then
    PAD_RIGHT=8
  fi
  echo $sid
  sketchybar --add space space.$sid left                                       \
             --set       space.$sid script="$PLUGIN_DIR/app_space.sh"          \
                                    associated_space=$sid                      \
                                    padding_left=$PAD_LEFT                     \
                                    padding_right=$PAD_RIGHT                   \
                                    background.color=${COLORS_SPACE[i]}        \
                                    background.border_width=0                  \
                                    background.corner_radius=6                 \
                                    background.height=24                       \
                                    icon=${ICONS_SPACE[i]}                     \
                                    icon.color=${COLORS_SPACE[i]}              \
                                    label="_"                                  \
                                    label.color=${COLORS_SPACE[i]}             \
             # --subscribe space.$sid front_app_switched window_change
             --subscribe space.$sid front_app_switched 
done

# Space bracket
sketchybar --add bracket spaces '/space\..*/'                      \
           --set         spaces background.color=$COLOR_BACKGROUND




# source $ITEM_DIR/front_app.sh
source $ITEM_DIR/calendar.sh
source $ITEM_DIR/wifi.sh
source $ITEM_DIR/battery.sh
source $ITEM_DIR/keyboard.sh
# source $ITEM_DIR/windows.sh
# source  $ITEM_DIR/mic.sh
sketchybar --update

